### ISSUE TITLE
A request to add a command to add mana to the current amount.

### ISSUE THREAD

**Issue by glebl1n** [ZettaSword/WizardryPlayerMana#4]
There is a command /setPlayerMana, but it sets the mana level, that is, if you have a maximum mana of 100, and you write /setMana 50, then no matter how much mana you have, it will become 50. I prithee you add a new command so that the player can add mana to its existing value. Let's say a player has 50\100 mana, the player writes a command and a value of 10, after which he has 60\100 mana.

**Comment by ZettaSword** [comment]
Done
