### ISSUE TITLE
Support for other mods that add bars to the HUD.

### ISSUE THREAD

**Issue by MagmaSlime123** [ZettaSword/WizardryPlayerMana#5]
Title. If a mod (such as Simple Difficulty or Elenai Dodge) adds a bar to the HUD, this mod's HUD should move, so it isn't hidden under/over another bar.

(I have the bar's position slightly moved to the left, to show the hidden Stamina bar (from the Elenai Dodging mod) underneath.)

![2024-08-06_00 17 55](https://github.com/user-attachments/assets/fb22341a-f562-4a10-a9d4-094553db5c39)

The last commit was 5 months ago. Please archive or remove this mod if you're no longer maintaining it.

**Comment by ZettaSword** [comment]
First of all, that's my mod, so i have rights to work on it or not update it.
Second of all, check latest version in config you have offset, allowing you to move gui freely.
